ReservationApp/Controllers/LoginController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
using ReservationApp.Extensions;
using ReservationApp.Models;
using ReservationApp.Resources;
using ReservationApp.Services.Interface;
using System.Diagnostics;

namespace ReservationApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILoginService _loginService;
        private readonly IEncryptService _encryptService;
        private readonly IStringLocalizer<LoginController> _localizer;

        public LoginController(IServiceProvider provider) 
        {
            this._localizer = provider.GetRequiredService<IStringLocalizer<LoginController>>();
            this._loginService = provider.GetRequiredService<ILoginService>();
            this._encryptService = provider.GetRequiredService<IEncryptService>();
        }

        public IActionResult LoginPage()
        {
            
            return View("~/Views/Login/AdminLogin.cshtml", new LoginModel());
        }

        public IActionResult AdminLoginPage()
        {
            return View("~/Views/Login/AdminLogin.cshtml", new LoginModel());
        }

        private void encryptTest()
        {
            string test = "Test";
            string encrypted = _encryptService.Encrypt(test);
            string decrypted = _encryptService.Decrypt(encrypted);
            Debug.WriteLine(encrypted + " " + decrypted);
        }

        public IActionResult Login(LoginModel model)
        {
            if(model != null && ModelState.IsValid)
            {
                return Json(true);
            }
            return Json(false);
        }

        public IActionResult AdminLogin(string jsonData)
        {
            bool result = false;
            string message = string.Empty;
            try
            {
                string decrypted = _encryptService.Decrypt(jsonData);
                var loginData = decrypted.ToObject<LoginModel>();
                result = _loginService.Login(loginData);
                message = _localizer["AdminLoginDone"] + "!"; //"管理者登入成功!";
            }
            catch (Exception ex)
            {
                result = false;
                message = ex.Message;
                //Response.StatusCode = 500;
            }
            var response = new
            {
                result,
                message
            };
            return Json(response.ToJson());
        }

        public IActionResult Logout()
        {
            try
            {
                if (_loginService.Logout())
                    return Redirect("/Home/Index");
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            return Json(false);
        }
    }
}

ReservationApp/Controllers/ManageOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using ReservationApp.Extensions;
using ReservationApp.Models.Entities;
using ReservationApp.Resources;
using ReservationApp.Services.Interface;

namespace ReservationApp.Controllers
{
    public class ManageOrderController : Controller
    {
        private IReadService _readService;
        private IUpdateService _updateService;
        private IDeleteService _deleteService;
        private readonly IEncryptService _encryptService;
        private readonly IStringLocalizer<ManageOrderController> _localizer;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public ManageOrderController(IServiceProvider provider)
        {
            this._localizer = provider.GetRequiredService<IStringLocalizer<ManageOrderController>>();
            this._sharedLocalizer = provider.GetRequiredService<IStringLocalizer<SharedResource>>();
            this._readService = provider.GetRequiredService<IReadService>();
            this._updateService = provider.GetRequiredService<IUpdateService>();
            this._deleteService = provider.GetRequiredService<IDeleteService>();
            this._encryptService = provider.GetRequiredService<IEncryptService>();
        }

        public IActionResult ManageOrder()
        {
            ViewBag.Controller = "/ManageOrder";
            return View();
        }

        [Authorize]
        public IActionResult ModifyReservationTime(string orderId)
        {
            try
            {
                Order? order = _readService.GetOrderByOrderId(orderId);
                if (order != null)
                {
                    ViewBag.OrderData = _encryptService.Encrypt(order.ToJson());
                    DateTime startDate = DateTime.Now.Date;
                    if(order.Reservations != null && order.Reservations.Count > 0)
                    {
                        startDate = order.Reservations.Min(r => r.Date).Date;

                        //If the start date exceeds the current date,
                        //it will allow selecting reservation date/time beyond 7 days from now.
                        startDate = startDate > DateTime.Now.Date ? DateTime.Now.Date : startDate;
                    }
                    var existedReservations = _readService.GetReservationsByDate(startDate, startDate.AddDays(7));
                    
                    ViewBag.ExistedReservations = _encryptService.Encrypt(existedReservations.ToJson());

                    ViewBag.NextUrl = "/ManageOrder/ConfirmModifyOrder";
                    ViewBag.StartDate = startDate;
                    return View("~/Views/Common/SelectReservationTime.cshtml");
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return Json(ex.Message);
            }
           
            return Json(false);
        }

        [Authorize]
        public IActionResult ConfirmModifyOrder(string orderId)
        {
            ViewBag.ReturnUrl = "/ManageOrder/ModifyOrder";
            ViewBag.Message = _localizer["ModifyOrder"] + "?"; //"編輯訂單?";
            ViewBag.ActionName = "ModifyOrder";
            return View("~/Views/Common/ConfirmOrder.cshtml");
        }

        [Authorize]
        public IActionResult ConfirmDeleteOrder(string orderId)
        {
            try
            {
                string orderData = string.Empty;
                Order? odata = _readService.GetOrderByOrderId(orderId);
                if (odata == null)
                {
                    //TODO 待測試
                    var message = _localizer["Invalid"] + _sharedLocalizer["OrderId"]; //"無效的訂單編號";
                    ViewBag.Message = message;
                    ViewBag.OrderData = null;
                    //Response.StatusCode = 500;
                    //return Json(message);
                    //ViewBag.Message = _localizer["Invalid"] + _sharedLocalizer["OrderId"]; //"無效的訂單編號";
                    //ViewBag.ActionName = "DeleteOrder";
                    //return View("~/Views/Common/ConfirmOrder.cshtml");
                }
                else
                {
                    ViewBag.OrderData = _encryptService.Encrypt(odata.ToJson());
                    ViewBag.ReturnUrl = "/ManageOrder/DeleteOrder";
                }
                
                //.Message = _localizer["DeleteOrder"]  + "?"; //"刪除訂單?";
                ViewBag.ActionName = "DeleteOrder";
                return View("~/Views/Common/ConfirmOrder.cshtml");
            }
            catch(Exception ex)
            {
                Response.StatusCode = 500;
                return Json(ex.Message);
            }
        }

        public IActionResult GetOrderList(string searchConditions)
        {
            try
            {
                var orders = _readService.GetOrderList(searchConditions);
                if (orders == null)
                {
                    orders = new List<Order>();
                }
                return PartialView("~/Views/PartialViews/_OrderListContent.cshtml", orders);
            }
            catch(Exception ex)
            {
                Response.StatusCode = 500;
                return Json(_localizer["SearchFailed"] + "!" + Environment.NewLine + ex.Message);
            }
        }

        [Authorize]
        public IActionResult ModifyOrder(string jsonData)
        {
            bool result = false;
            string message = string.Empty;
            try
            {
                result = _updateService.ModifyOrder(_encryptService.Decrypt(jsonData));
                message = "";// _localizer["ModifyOrderDone"]; //"訂單修改完成";
            }
            catch (Exception ex)
            {
                result = false;
                /*
                message = _localizer["ModifyOrderFail"]; //"訂單修改失敗!";
                if (ex.Message != string.Empty)
                    message += Environment.NewLine + ex.Message;*/
                message = ex.Message;
            }
            //If modify failed, message = reason of failure
            var response = new {
                result,
                message
            };
            return Json(response.ToJson());
        }

        [Authorize]
        public IActionResult DeleteOrder(string jsonData)
        {
            bool result = false;
            string message = string.Empty;
            try {
                var decrypted = _encryptService.Decrypt(jsonData);
                result = _deleteService.DeleteOrder(decrypted);
                message = "";// _localizer["DeletOrderDone"]; //"訂單刪除完成";
            }
            catch (Exception ex)
            {
                result = false;
                /*
                message = _localizer["DeletOrderFail"]; //"訂單刪除失敗!";
                
                if (ex.Message != string.Empty)
                    message += Environment.NewLine + ex.Message;
                */
                message = ex.Message;
            }
            //If delete failed, message = reason of failure
            var response = new { 
                result, 
                message
            };
            return Json(response.ToJson());
        }
    }
}

ReservationApp/Controllers/NewOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using NuGet.Protocol;
using ReservationApp.Extensions;
using ReservationApp.Resources;
using ReservationApp.Services;
using ReservationApp.Services.Interface;

namespace ReservationApp.Controllers
{
    public class NewOrderController : Controller
    {
        private ICreateService _createService;
        private readonly IEncryptService _encryptService;
        private IReadService _readService;
        private readonly IStringLocalizer<NewOrderController> _localizer;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public NewOrderController(IServiceProvider provider) 
        {
            this._localizer = provider.GetRequiredService<IStringLocalizer<NewOrderController>>();
            this._sharedLocalizer = provider.GetRequiredService<IStringLocalizer<SharedResource>>();
            this._readService = provider.GetRequiredService<IReadService>();
            this._createService = provider.GetRequiredService<ICreateService>();
            this._encryptService = provider.GetRequiredService<IEncryptService>();
        }

        public IActionResult Index()
        {
            //return View("~/Views/PartialViews/_TimeTable_rwd.cshtml");
            try
            {
                DateTime startDate = DateTime.Now.AddDays(-1);
                var rdatas = _readService.GetReservationsByDate(startDate, startDate.AddDays(7));
                if (rdatas == null || rdatas.Count() == 0)
                    ViewBag.ExistedReservations = null;
                else
                {
                    var test = _encryptService.Encrypt(rdatas.ToJson());
                    ViewBag.ExistedReservations = test;
                }
                ViewBag.NextUrl = "/NewOrder/InputUserData";
                ViewBag.StartDate = startDate.Date;
                return View("~/Views/Common/SelectReservationTime.cshtml");
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500; 
                return Json(ex.Message);
            }
        }

      

        public IActionResult AddNewOrder(string jsonData)
        {
            bool result = false;
            string message = string.Empty;
            try
            {
                var decrypted = _encryptService.Decrypt(jsonData);
                result = _createService.AddNewOrder(decrypted, out string orderId);
                //message = "訂單建立完成!" + Environment.NewLine + "訂單編號 : " + orderId;
                //message = _localizer["AddOrderDone"] + "!" + "\n" + _sharedLocalizer["OrderId"] + " : " + orderId;
                message = orderId;
            }
            catch(Exception ex)
            {
                result = false;
                //message = "訂單建立失敗!";
                /*
                message = _localizer["AddOrderFail"] + "!";
                if (ex.Message != string.Empty)
                    message += Environment.NewLine + ex.Message;*/
                message = ex.Message;
            }
            //If add successed, message = orderId
            //If add failed, message = reason of failure
            var response = new { 
                result, 
                message
            };
            return Json(response.ToJson());
        }

        public IActionResult InputUserData()
        {
            return View();
        }

        public IActionResult ConfirmOrder()
        {
            ViewBag.ReturnUrl = "/NewOrder/AddNewOrder";
            //ViewBag.Message = "建立訂單?";
            ViewBag.Message = _localizer["AddOrder"] + "?";
            ViewBag.ActionName = "AddOrder";
            return View("~/Views/Common/ConfirmOrder.cshtml");
        }
    }
}

ReservationApp/Views/Shared/_DateFormat.cshtml
@model System.DateTime

<!--Template for display datetime-->
@Model.ToString("yyyy/MM/dd")

ReservationApp/Views/Shared/_Layout.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

<!DOCTYPE html>
<html lang=@System.Threading.Thread.CurrentThread.CurrentCulture.Name>
<head>
    <title>ReservationApp</title>
    <meta charset="utf-8"/>
    <meta name="google" content="notranslate"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservationApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReservationApp.styles.css" asp-append-version="true" />
    
    <script src="~/lib/jquery/dist/jquery-3.7.0.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/js/_Layout.js"></script>
    <link rel="stylesheet" href="/css/_Layout.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReservationApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link light_effect" asp-area="" asp-controller="Home" asp-action="Index">@_localizer["MenuItem_Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link light_effect" asp-area="" asp-controller="NewOrder" asp-action="Index">@_localizer["MenuItem_NewOrder"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link light_effect" asp-area="" asp-controller="ManageOrder" asp-action="ManageOrder">@_localizer["MenuItem_ManageOrder"]</a>
                        </li>
                    </ul>
                    <div class="ml-auto">
                        <ul class="navbar-nav">
                            <li class="nav-item" id="loginButton">
                                @if (User.Identity != null && User.Identity.IsAuthenticated)
                                {
                                    <a id="logout_btn" class="nav-link light_effect" asp-area="" asp-controller="Login" asp-action="Logout">@_localizer["MenuItem_Logout"] ( @User.Identity.Name )</a>
                                }
                                else
                                {
                                    <a id="login_btn" class="nav-link light_effect" asp-area="" asp-controller="Login" asp-action="AdminLoginPage">@_localizer["MenuItem_Login"]</a>
                                }
                            </li>
                            <li class="nav-item">
                                <div id="currentCulture" class="hidden">@System.Threading.Thread.CurrentThread.CurrentCulture.Name</div>
                                <div class="dropdown" style="width:120px;">
                                    <select id="languageSelector" class="form-select" >
                                        @if (System.Threading.Thread.CurrentThread.CurrentCulture.Name == "zh-TW")
                                        {
                                            <option class="languageOption" value="zh-TW">zh-TW</option>
                                        }
                                        else
                                        {
                                            <option class="languageOption" value="zh-Hant">zh-Hant</option>
                                        }
                                        <option class="languageOption" value="en-US">en-US</option>
                                    </select>
                                    <!--
                                    <a id="languageSelector" class="nav-link text-dark" role="button" data-bs-toggle="dropdown" aria-expanded="false">@_localizer["MenuItem_Language"]</a>
                                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="languageSelector">
                                        <li><a id="language_zh-TW" class="dropdown-item">zh-TW</a></li>
                                        <li><a id="language_en-US" class="dropdown-item">en-US</a></li>
                                    </ul>-->
                                </div>
                            </li>
                            
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            ReservationApp © 2023 Benlin.
        </div>
    </footer>
    <!--<script src="~/lib/jquery/dist/jquery-3.7.0.min.js"></script>
    <!--<script src="/js/jquery-3.7.0.min.js"></script>-->
    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>-->
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ReservationApp/Views/Shared/_MessageDialog.cshtml
<link rel="stylesheet" href="~/lib/jquery.ui.combined/1.13.2/Content/Content/themes/base/jquery-ui.css" />
<script src="~/lib/jquery.ui.combined/1.13.2/Content/Scripts/jquery-ui-1.13.2.min.js"></script>
<script src="/js/_MessageDialog.js"></script>

<div id="messageDialog" class="hidden" title="title"><p>message</p></div>

<div id="messageDialogCulture" class="hidden">@System.Threading.Thread.CurrentThread.CurrentCulture.Name</div>